
version: 2

models:
  - name: concat
    description: "connecting with fivetran"
    database: FIVETRAN_DB
    schema: FIVETRAN_SCHEMA
    tables:
    - name: concat
      description: "This is the concat model"