
version: 2
sources:
  - name: EMPLOYEE_DATA_SHEET
    database: FIVETRAN_DB
    schema: EMPLOYEE_DATA_SHEET
    tables:
        - name: EMPLOYEE_DATA
    
models:
  - name: concat
    description: "concat first and last name"